[twitter]
apikey      = ""
apisecret   = ""
token       = ""
tokensecret = ""

[wallet]
rpchost     = "0.0.0.0"
rpcport     = "8332"
rpcuser     = "moya4"
rpcpassword = "moya4pass"

[database]
host     = "0.0.0.0"
port     = "5432"
user     = "docker"
password = "docker"